inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - example-app/**/*
    - LLMAgent/**/*
    - Docs/**/*
    - db/cache_schema.rb
    - db/queue_schema.rb
    - db/cable_schema.rb
    - bin/**/*
    - node_modules/**/*
    - vendor/**/*
